### PR TITLE
Fix build with Apple Clang

### PR DESCRIPTION
**Pull request by jakepetroules**

### CODE REVIEW

**Comment by peterbudai** [comment]
The missing newline is ok, but I don't see why it wouldn't compile with Clang with `size_t`s instead of `unsigned int`s. I've also compiled it with Clang and it went fine. What was the error at your side?

**Comment by jakepetroules** [comment]
The function to which this parameter is passed takes an unsigned int. Attempting to pass a size_t results in a signature mismatch. You'd think it would just shorten, but I guess newer versions of Clang have gotten more strict? I believe Apple Clang 5.x was the earliest version I tried with, let me check right now with 5.1.1...

**Comment by jakepetroules** [comment]
Without this patch:

```
$ clang++ -v
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.3.0
Thread model: posix
$ clang tools/tinf/*.c -dynamiclib -o libtinf.dylib
$ clang++ -std=c++11 -stdlib=libc++ -dynamiclib -Itools/tinf *.cpp -L. -ltinf
init.cpp:84:6: error: no matching function for call to 'tinf_gzip_uncompress'
        if (tinf_gzip_uncompress(raw.get(), &dsize, frequency_lists, frequency_lists_size) != TINF_OK) {
            ^~~~~~~~~~~~~~~~~~~~
./tools/tinf/tinf.h:38:12: note: candidate function not viable: no known conversion from 'size_t *' (aka 'unsigned long *') to 'unsigned int *' for 2nd argument
int TINFCC tinf_gzip_uncompress(void *dest, unsigned int *destLen,
           ^
init.cpp:125:6: error: no matching function for call to 'tinf_gzip_uncompress'
        if (tinf_gzip_uncompress(raw.get(), &dsize, adjacency_graphs, adjacency_graphs_size) != TINF_OK) {
            ^~~~~~~~~~~~~~~~~~~~
./tools/tinf/tinf.h:38:12: note: candidate function not viable: no known conversion from 'size_t *' (aka 'unsigned long *') to 'unsigned int *' for 2nd argument
int TINFCC tinf_gzip_uncompress(void *dest, unsigned int *destLen,
           ^
2 errors generated.
```

With this patch, compiles cleanly.

**Comment by peterbudai** [comment]
I see what you're talking about now. I can't recall the Clang version I was using, but I guess it was an older one. Tomorrow I'll check whether it still compiles on my other environments, and if so I'll merge this one. Thanks for the improvement.

**Comment by jakepetroules** [comment]
Sounds good, thanks.

**Pull request merged**
